#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 23, 2020 02:24:30 PM EDT  platform: Linux

import sys
import parserXML

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global cb_singleFile
    cb_singleFile = tk.IntVar()
    global cb_enableCore
    cb_enableCore = tk.IntVar()
    global cb_enableRoyal
    cb_enableRoyal = tk.IntVar()
    global cb_enableWorkshop
    cb_enableWorkshop = tk.IntVar()
    global eb_timeout
    eb_timeout = tk.StringVar()
    global msg_output
    msg_output = tk.StringVar()
    msg_output.set('')
    global progressBar
    progressBar = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def setProgress(message, progress):
    msg_output.set(message)
    progressBar.set(progress)
    top_level.update()


def run():
    if str(eb_timeout.get()).isnumeric():
        parserXML.TIMEOUT_VAL = int(eb_timeout.get())
    if cb_enableCore.get():
        parserXML.DEFS.append(parserXML.DIR_CORE_DEFS)
    if cb_enableRoyal.get():
        parserXML.DEFS.append(parserXML.DIR_ROYAL_DEFS)
    if cb_enableWorkshop.get():
        parserXML.DEFS.append(parserXML.DIR_WORKSHOP_DEFS)
    if cb_singleFile.get():
        parserXML.SINGLE_FILE = True
 
    parserXML.run()
    parserXML.DEFS.clear()
    sys.stdout.flush()

def destroy_window():
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import rimsheets
    rimsheets.vp_start_gui()




